"""add imagenes and video columns to ejercicios

Revision ID: 09bcc26b2064
Revises: 015
Create Date: 2026-08-28 17:46:35.613422

Nota: esta migracion se volvio idempotente porque en al menos un entorno
(dev de Miguel) la columna "ejercicios.imagenes" ya existia en la base de
datos real aunque la tabla alembic_version seguia marcada en "015" (drift
entre esquema real e historial de Alembic, probablemente por una corrida
parcial anterior). Cada operacion ahora verifica el estado actual del
esquema con SQLAlchemy Inspector antes de aplicarse, para que "alembic
upgrade head" nunca falle con DuplicateColumn/DuplicateTable/UndefinedObject
sin importar en que punto haya quedado la base de datos.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09bcc26b2064'
down_revision: Union[str, None] = '015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _inspector():
    bind = op.get_bind()
    return sa.inspect(bind)


def _has_column(table: str, column: str) -> bool:
    insp = _inspector()
    return any(c["name"] == column for c in insp.get_columns(table))


def _has_index(table: str, index: str) -> bool:
    insp = _inspector()
    return any(i["name"] == index for i in insp.get_indexes(table))


def _has_unique_constraint(table: str, constraint: str) -> bool:
    insp = _inspector()
    return any(c["name"] == constraint for c in insp.get_unique_constraints(table))


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not _has_column('ejercicios', 'imagenes'):
        op.add_column('ejercicios', sa.Column('imagenes', sa.JSON(), nullable=True))
    if not _has_column('ejercicios', 'video'):
        op.add_column('ejercicios', sa.Column('video', sa.Text(), nullable=True))

    if _has_index('facturas_suscripcion', op.f('ix_facturas_estado')):
        op.drop_index(op.f('ix_facturas_estado'), table_name='facturas_suscripcion')
    if _has_index('facturas_suscripcion', op.f('ix_facturas_id_suscripcion')):
        op.drop_index(op.f('ix_facturas_id_suscripcion'), table_name='facturas_suscripcion')
    if _has_index('facturas_suscripcion', op.f('ix_facturas_referencia_externa')):
        op.drop_index(op.f('ix_facturas_referencia_externa'), table_name='facturas_suscripcion')
    if _has_unique_constraint('facturas_suscripcion', op.f('uq_facturas_referencia_externa')):
        op.drop_constraint(op.f('uq_facturas_referencia_externa'), 'facturas_suscripcion', type_='unique')

    if not _has_index('facturas_suscripcion', op.f('ix_facturas_suscripcion_id_suscripcion')):
        op.create_index(op.f('ix_facturas_suscripcion_id_suscripcion'), 'facturas_suscripcion', ['id_suscripcion'], unique=False)
    if not _has_index('facturas_suscripcion', op.f('ix_facturas_suscripcion_referencia_externa')):
        op.create_index(op.f('ix_facturas_suscripcion_referencia_externa'), 'facturas_suscripcion', ['referencia_externa'], unique=True)

    if _has_index('suscripciones', op.f('ix_suscripciones_estado')):
        op.drop_index(op.f('ix_suscripciones_estado'), table_name='suscripciones')
    if _has_index('tipos_membresia', op.f('ix_tipos_membresia_fecha_fin_promo')):
        op.drop_index(op.f('ix_tipos_membresia_fecha_fin_promo'), table_name='tipos_membresia')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not _has_index('tipos_membresia', op.f('ix_tipos_membresia_fecha_fin_promo')):
        op.create_index(op.f('ix_tipos_membresia_fecha_fin_promo'), 'tipos_membresia', ['fecha_fin_promo'], unique=False)
    if not _has_index('suscripciones', op.f('ix_suscripciones_estado')):
        op.create_index(op.f('ix_suscripciones_estado'), 'suscripciones', ['estado'], unique=False)

    if _has_index('facturas_suscripcion', op.f('ix_facturas_suscripcion_referencia_externa')):
        op.drop_index(op.f('ix_facturas_suscripcion_referencia_externa'), table_name='facturas_suscripcion')
    if _has_index('facturas_suscripcion', op.f('ix_facturas_suscripcion_id_suscripcion')):
        op.drop_index(op.f('ix_facturas_suscripcion_id_suscripcion'), table_name='facturas_suscripcion')

    if not _has_unique_constraint('facturas_suscripcion', op.f('uq_facturas_referencia_externa')):
        op.create_unique_constraint(op.f('uq_facturas_referencia_externa'), 'facturas_suscripcion', ['referencia_externa'], postgresql_nulls_not_distinct=False)
    if not _has_index('facturas_suscripcion', op.f('ix_facturas_referencia_externa')):
        op.create_index(op.f('ix_facturas_referencia_externa'), 'facturas_suscripcion', ['referencia_externa'], unique=False)
    if not _has_index('facturas_suscripcion', op.f('ix_facturas_id_suscripcion')):
        op.create_index(op.f('ix_facturas_id_suscripcion'), 'facturas_suscripcion', ['id_suscripcion'], unique=False)
    if not _has_index('facturas_suscripcion', op.f('ix_facturas_estado')):
        op.create_index(op.f('ix_facturas_estado'), 'facturas_suscripcion', ['estado'], unique=False)

    if _has_column('ejercicios', 'video'):
        op.drop_column('ejercicios', 'video')
    if _has_column('ejercicios', 'imagenes'):
        op.drop_column('ejercicios', 'imagenes')
    # ### end Alembic commands ###
