"""add imagenes and video columns to ejercicios

Revision ID: 09bcc26b2064
Revises: 015
Create Date: 2026-08-28 17:46:35.613422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09bcc26b2064'
down_revision: Union[str, None] = '015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ejercicios', sa.Column('imagenes', sa.JSON(), nullable=True))
    op.add_column('ejercicios', sa.Column('video', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_facturas_estado'), table_name='facturas_suscripcion')
    op.drop_index(op.f('ix_facturas_id_suscripcion'), table_name='facturas_suscripcion')
    op.drop_index(op.f('ix_facturas_referencia_externa'), table_name='facturas_suscripcion')
    op.drop_constraint(op.f('uq_facturas_referencia_externa'), 'facturas_suscripcion', type_='unique')
    op.create_index(op.f('ix_facturas_suscripcion_id_suscripcion'), 'facturas_suscripcion', ['id_suscripcion'], unique=False)
    op.create_index(op.f('ix_facturas_suscripcion_referencia_externa'), 'facturas_suscripcion', ['referencia_externa'], unique=True)
    op.drop_index(op.f('ix_suscripciones_estado'), table_name='suscripciones')
    op.drop_index(op.f('ix_tipos_membresia_fecha_fin_promo'), table_name='tipos_membresia')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tipos_membresia_fecha_fin_promo'), 'tipos_membresia', ['fecha_fin_promo'], unique=False)
    op.create_index(op.f('ix_suscripciones_estado'), 'suscripciones', ['estado'], unique=False)
    op.drop_index(op.f('ix_facturas_suscripcion_referencia_externa'), table_name='facturas_suscripcion')
    op.drop_index(op.f('ix_facturas_suscripcion_id_suscripcion'), table_name='facturas_suscripcion')
    op.create_unique_constraint(op.f('uq_facturas_referencia_externa'), 'facturas_suscripcion', ['referencia_externa'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_facturas_referencia_externa'), 'facturas_suscripcion', ['referencia_externa'], unique=False)
    op.create_index(op.f('ix_facturas_id_suscripcion'), 'facturas_suscripcion', ['id_suscripcion'], unique=False)
    op.create_index(op.f('ix_facturas_estado'), 'facturas_suscripcion', ['estado'], unique=False)
    op.drop_column('ejercicios', 'video')
    op.drop_column('ejercicios', 'imagenes')
    # ### end Alembic commands ###
